# Makefile for example Arduino projects

build:
	cd cBlinkBuzz && make
	cd aBlinkBuzz && make

clean:
	cd cBlinkBuzz && make clean
	cd aBlinkBuzz && make clean

install:
	sudo cp include/AVR* /usr/local/include
